using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Simulator.Generators
{
    public class CongruentialGenerator
    {
        public float Generate()
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Generates a random number.
        /// </summary>
        /// <param name="a"></param>
        /// <param name="M">The max. value generated by the sequence.</param>
        /// <param name="x0">The integer sequence.</param>
        /// <returns></returns>
        public float[] Generate(int a, int M, float x0)
        {
            float[] x = new float[M + 1];

            x[0] = x0;
            for (int i = 1; i < M; i++)
            {
                x[i] = a * x[i - 1] % M;
            }

            return x;
        }
    }
}
